# produce a CI workflow yml for maven project that produces a message saying that the build is successful, otherwise it will produce a message saying that the build has failed

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: xxxxxxxxxxxxxxxx@xx
    - name: Set up JDK 11
      uses: xxxxxxxxxxxxxxxxxx@xx
      with:
        java-version: '11'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with Maven
      run: mvn test
    - name: Check for build success
      run: |
        if [ -f target/surefire-reports/*.xml ]; then
          echo "Build successful"
        else
          echo "Build failed"
          exit 1
        fi

